### ISSUE TITLE
panic: unknown update level

### ISSUE THREAD

**Issue by myles-mcdonnell** [ktr0731/evans#109]
running 0.6.3 on fedora 28 (amd64)

```
evans -p 8150 api/service.proto                   
panic: unknown update level

goroutine 34 [running]:
github.com/ktr0731/evans/adapter/controller.newUpdater(0xc42022b6c0, 0xc4200b2810, 0xc38f60, 0xc4202b6030, 0x0)
        /go/src/github.com/ktr0731/evans/adapter/controller/updater.go:139 +0x1a9
github.com/ktr0731/evans/adapter/controller.checkUpdate.func1(0x100d380, 0xc377a0, 0xc42022b740, 0xc4202c4000, 0xc42022b6c0)
        /go/src/github.com/ktr0731/evans/adapter/controller/updater.go:58 +0x1c0
created by github.com/ktr0731/evans/adapter/controller.checkUpdate
        /go/src/github.com/ktr0731/evans/adapter/controller/updater.go:25 +0xa3

```

**Comment by ktr0731** [comment]
Can you show me the config file?
If you didn't change anything, there is in `~/.config/evans/config.toml`.
