### ISSUE TITLE
0.9.2 Evans cli error occurs with panic: interrupted system call

### ISSUE THREAD

**Issue by Ghun2** [ktr0731/evans#355]
## Describe the bug
Mac Big Sur 11.1 terminal was testing the grpc app using Evans cli. The service was selected and a function was being called to enter a value, but it was terminated with a 
`panic: interrupted system call`
I get the same result when I reboot the computer. The most suspicious cause seems to be the update from version 0.9.1 to version 0.9.2. Please solve it.

## Screenshots

```

  ______
 |  ____|
 | |__    __   __   __ _   _ __    ___
 |  __|   \ \ / /  / _. | | '_ \  / __|
 | |____   \ V /  | (_| | | | | | \__ \
 |______|   \_/    \__,_| |_| |_| |___/

 more expressive universal gRPC client


drsalary@127.0.0.1:50051> header authorization="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjMzMTM3NjkxOTgyLCJ1c2VyX2lkIjoyfQ.osYUi7Okmz_BCITTzAHp3tYDkyelKNIJl6OAAsiEero"

drsalary@127.0.0.1:50051> service WorkContractService

drsalary.WorkContractService@127.0.0.1:50051> call CreateContract
workcontract::cont_id (TYPE_UINT32) =>
workcontract::user_id (TYPE_UINT32) => 2
workcontract::shop_id (TYPE_UINT32) => 0
workcontract::cont_name (TYPE_STRING) => test01
workcontract::cont_date (TYPE_STRING) => 20200701
workcontract::retire_date (TYPE_STRING) =>
workcontract::d1_start_pot (TYPE_STRING) => 09:00
workcontract::d1_end_pot (TYPE_STRING) => 18:00
Good Bye :)
panic: interrupted system call

goroutine 1 [running]:
github.com/ktr0731/go-prompt.NewStandardInputParser(0x1b48c80)
	/Users/ktr/.ghq/pkg/mod/github.com/ktr0731/go-prompt@v0.2.2-0.20190609072126-7894cc3f2925/input_posix.go:85 +0xa5
github.com/ktr0731/go-prompt.New(0x1a5efb8, 0x1a5eea8, 0x0, 0x0, 0x0, 0x174a38d)
	/Users/ktr/.ghq/pkg/mod/github.com/ktr0731/go-prompt@v0.2.2-0.20190609072126-7894cc3f2925/option.go:243 +0x65
github.com/ktr0731/go-prompt.Input(0xc0004e0a50, 0x2b, 0x1a5eea8, 0xc0001c20a0, 0xc, 0x14, 0xa, 0x14, 0xc0004e0a50, 0x2b)
	/Users/ktr/.ghq/pkg/mod/github.com/ktr0731/go-prompt@v0.2.2-0.20190609072126-7894cc3f2925/shortcut.go:7 +0x4c
github.com/ktr0731/evans/prompt.(*prompt).Input(0xc0004c8c40, 0x26, 0x1a220b0, 0x6, 0xc00022ee1f)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/prompt/prompt.go:123 +0x12c
github.com/ktr0731/evans/fill/proto.(*InteractiveFiller).inputPrimitiveField(0xc0004826c0, 0xc000000009, 0x2b, 0xc00052d4a0, 0x1, 0x1)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/fill/proto/interactive_filler.go:308 +0x37
github.com/ktr0731/evans/fill/proto.(*InteractiveFiller).inputField(0xc0004826c0, 0xc0001c48a0, 0xc000540600, 0xc00007c000, 0x0, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/fill/proto/interactive_filler.go:219 +0xc92
github.com/ktr0731/evans/fill/proto.(*InteractiveFiller).inputMessage(0xc0004826c0, 0xc0001c48a0, 0x0, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/fill/proto/interactive_filler.go:91 +0x20d
github.com/ktr0731/evans/fill/proto.(*InteractiveFiller).inputField(0xc0004826c0, 0xc0001c45d0, 0xc00054e800, 0x0, 0x0, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/fill/proto/interactive_filler.go:191 +0x206
github.com/ktr0731/evans/fill/proto.(*InteractiveFiller).inputMessage(0xc0004826c0, 0xc0001c45d0, 0x0, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/fill/proto/interactive_filler.go:91 +0x20d
github.com/ktr0731/evans/fill/proto.(*InteractiveFiller).Fill(0xc0004826c0, 0x1a1da20, 0xc0001c45d0, 0x0, 0x19b1000, 0xc0000b9201)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/fill/proto/interactive_filler.go:50 +0xec
github.com/ktr0731/evans/usecase.(*dependencyManager).CallRPCInteractively.func1(0x1a1da20, 0xc0001c45d0, 0xc0001c45d0, 0xc00054c780)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/usecase/call_rpc.go:434 +0x57
github.com/ktr0731/evans/usecase.(*interactiveFiller).Fill(0xc0003a6028, 0x1a1da20, 0xc0001c45d0, 0xc00053d000, 0xc0000b9318)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/usecase/call_rpc.go:424 +0x3d
github.com/ktr0731/evans/usecase.(*dependencyManager).CallRPC.func1(0x19909a0, 0xc0004ba240, 0x1c, 0xc000038300)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/usecase/call_rpc.go:59 +0x7e
github.com/ktr0731/evans/usecase.(*dependencyManager).CallRPC(0xc0004fe980, 0x1b3a6c0, 0xc00003a0e0, 0x1b2a6c0, 0xc00000e018, 0xc000038300, 0xe, 0x1b28de0, 0xc0003a6028, 0x0, ...)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/usecase/call_rpc.go:384 +0xcd4
github.com/ktr0731/evans/usecase.(*dependencyManager).CallRPCInteractively(0xc0004fe980, 0x1b3a6c0, 0xc00003a0e0, 0x1b2a6c0, 0xc00000e018, 0xc000038300, 0xe, 0x18b0000, 0x1a28801, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/usecase/call_rpc.go:432 +0x105
github.com/ktr0731/evans/usecase.CallRPCInteractively(...)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/usecase/call_rpc.go:428
github.com/ktr0731/evans/repl.(*callCommand).Run(0xc000304548, 0x1b2a6c0, 0xc00000e018, 0xc00052cf20, 0x1, 0x1, 0x0, 0xc0004ca900)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/repl/commands.go:201 +0x2d6
github.com/ktr0731/evans/repl.(*REPL).runCommand(0xc0004bca00, 0xc0003a4048, 0x4, 0xc00052cf20, 0x1, 0x1, 0x0, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/repl/repl.go:156 +0x1dd
github.com/ktr0731/evans/repl.(*REPL).Run(0xc0004bca00, 0x1b3a680, 0xc0004bc7c0, 0x0, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/repl/repl.go:111 +0x22e
github.com/ktr0731/evans/mode.RunAsREPLMode(0xc00033f260, 0x1b3d940, 0xc0003636b0, 0xc000312370, 0x0, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/mode/repl.go:68 +0x819
github.com/ktr0731/evans/app.runREPLCommand(0xc0003647e0, 0x1b3d940, 0xc0003636b0, 0x0, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/app/commands.go:273 +0x265
github.com/ktr0731/evans/app.newREPLCommand.func1(0xc000320b00, 0xc0003647e0, 0x0, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/app/commands.go:241 +0x76
github.com/ktr0731/evans/app.runFunc.func1(0xc000320b00, 0xc000314a20, 0x0, 0x3, 0x0, 0x0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/app/commands.go:87 +0x1d7
github.com/spf13/cobra.(*Command).execute(0xc000320b00, 0xc0003149f0, 0x3, 0x3, 0xc000320b00, 0xc0003149f0)
	/Users/ktr/.ghq/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002b7b80, 0x0, 0xc0001dfe98, 0x100df18)
	/Users/ktr/.ghq/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ktr/.ghq/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/ktr0731/evans/app.(*App).Run(0xc00014bf60, 0xc0000300b0, 0x4, 0x4, 0xc000269da0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/app/app.go:51 +0xd7
main.main()
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/main.go:11 +0xfb
```

## Environment
- OS: Mac Big Sur 11.1 
- Terminal: zsh
- Evans version: 0.9.2
- `protoc` version: libprotoc 3.14.0
- `protoc` plugin version (if you are using):

**Comment by ktr0731** [comment]
I tried to reproduce the bug with macOS Big Sur 11.1 and Evans v0.9.2, but could not.
If you can provide more described context, please reopen this issue.
