### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by jfgosselin** [ktr0731/evans#688]
## To reproduce
Started to get this stacktrace out of nowhere , even after re-install it 

```
~  evans -r repl
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
google.golang.org/grpc/internal/metadata.Validate(0x1050dce10?)
	/Users/ktr/.ghq/pkg/mod/google.golang.org/grpc@v1.51.0/internal/metadata/metadata.go:88 +0x214
google.golang.org/grpc.newClientStream({0x1050dce10, 0x14000235c20}, 0x1056215a0, 0x14000333180, {0x104dfad15, 0x3e}, {0x0, 0x0, 0x0})
	/Users/ktr/.ghq/pkg/mod/google.golang.org/grpc@v1.51.0/stream.go:172 +0x5c
google.golang.org/grpc.(*ClientConn).NewStream(0x140001cf438?, {0x1050dce10?, 0x14000235c20?}, 0x104ffae60?, {0x104dfad15?, 0x14000235c20?}, {0x0?, 0x104c526d4?, 0x1050dceb8?})
	/Users/ktr/.ghq/pkg/mod/google.golang.org/grpc@v1.51.0/stream.go:162 +0x154
google.golang.org/grpc/reflection/grpc_reflection_v1alpha.(*serverReflectionClient).ServerReflectionInfo(0x1050dceb8?, {0x1050dce10?, 0x14000235c20?}, {0x0?, 0x140001cf4d8?, 0x104c524bc?})
	/Users/ktr/.ghq/pkg/mod/google.golang.org/grpc@v1.51.0/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go:55 +0x68
github.com/jhump/protoreflect/grpcreflect.(*Client).initStreamLocked(0x14000278b00)
	/Users/ktr/.ghq/pkg/mod/github.com/jhump/protoreflect@v1.14.0/grpcreflect/client.go:571 +0x1ac
github.com/jhump/protoreflect/grpcreflect.(*Client).doSendLocked(0x14000278b00, 0x0, {0x0?, 0x0?}, 0x1050da100?)
	/Users/ktr/.ghq/pkg/mod/github.com/jhump/protoreflect@v1.14.0/grpcreflect/client.go:524 +0xdc
github.com/jhump/protoreflect/grpcreflect.(*Client).doSend(0x50?, 0x105636c40?)
	/Users/ktr/.ghq/pkg/mod/github.com/jhump/protoreflect@v1.14.0/grpcreflect/client.go:511 +0xd8
github.com/jhump/protoreflect/grpcreflect.(*Client).send(0x140001cf658?, 0x1400034c8f8?)
	/Users/ktr/.ghq/pkg/mod/github.com/jhump/protoreflect@v1.14.0/grpcreflect/client.go:483 +0x1c
github.com/jhump/protoreflect/grpcreflect.(*Client).ListServices(0x140001cf708?)
	/Users/ktr/.ghq/pkg/mod/github.com/jhump/protoreflect@v1.14.0/grpcreflect/client.go:464 +0x88
github.com/ktr0731/evans/grpc/grpcreflection.(*client).ListPackages(0x1400000f098)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/_tmp/worktree2/grpc/grpcreflection/reflection.go:62 +0x2c
github.com/ktr0731/evans/idl/proto.LoadByReflection({0x12cdce748?, 0x1400034c8e0?})
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/_tmp/worktree2/idl/proto/proto.go:148 +0x2c
github.com/ktr0731/evans/mode.newSpec(0x1400033a3f0?, {0x12cdce748?, 0x1400034c8e0?})
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/_tmp/worktree2/mode/common.go:18 +0x38
github.com/ktr0731/evans/mode.RunAsREPLMode(0x1400033a3f0, {0x1050dec38, 0x1400035e0a0}, 0x140002357c0)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/_tmp/worktree2/mode/repl.go:26 +0xc4
github.com/ktr0731/evans/app.runREPLCommand(0x1400033bdd0, {0x1050dec38?, 0x1400035e0a0})
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/_tmp/worktree2/app/commands.go:280 +0x274
github.com/ktr0731/evans/app.newREPLCommand.func1(0x0?, 0x1400033bdd0?)
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/_tmp/worktree2/app/commands.go:248 +0xdc
github.com/ktr0731/evans/app.runFunc.func1(0x1400032af00, {0x140002fd9c0, 0x0, 0x1})
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/_tmp/worktree2/app/commands.go:87 +0x12c
github.com/spf13/cobra.(*Command).execute(0x1400032af00, {0x140002fd9b0, 0x1, 0x1})
	/Users/ktr/.ghq/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x1400032a000)
	/Users/ktr/.ghq/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ktr/.ghq/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/ktr0731/evans/app.(*App).Run(0x140001cff50, {0x140000300d0?, 0x2, 0x1047550ac?})
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/_tmp/worktree2/app/app.go:51 +0x1a4
main.main()
	/Users/ktr/.ghq/src/github.com/ktr0731/evans/_tmp/worktree2/main.go:11 +0xa8
```

## Environment
- OS: Sonoma 14.2.1
- Terminal: zsh
- Evans version: 0.10.11

**Comment by jfgosselin** [comment]
config.toml was corrupted ...
